# Generated by Django 2.1.1 on 2020-04-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200426_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signature',
        ),
    ]
