# Generated by Django 2.1.1 on 2020-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
