# Generated by Django 2.1.7 on 2020-06-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200628_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follows',
            new_name='friends',
        ),
    ]
