# Generated by Django 2.1.7 on 2020-06-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200629_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_img',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='profile_pics'),
        ),
    ]
